module github.com/Mouglie/mpmoi-engine

go 1.25.0

toolchain go1.26.5

require (
	github.com/lib/pq v1.12.3
	github.com/mdp/qrterminal/v3 v3.2.1
	github.com/rs/zerolog v1.35.1
	go.mau.fi/mautrix-meta v0.0.0
	go.mau.fi/mautrix-signal v0.0.0
	go.mau.fi/mautrix-whatsapp v0.0.0
	go.mau.fi/util v0.9.12-0.20260719092501-f9c03d846391
	go.mau.fi/whatsmeow v0.0.0-20260718134955-fac667d55293
	gopkg.in/yaml.v3 v3.0.1
	maunium.net/go/mautrix v0.29.1-0.20260719130752-5743d9b6f27e
	modernc.org/sqlite v1.56.0
	rsc.io/qr v0.2.0
)

require (
	filippo.io/edwards25519 v1.2.0 // indirect
	github.com/HugoSmits86/nativewebp v1.3.0 // indirect
	github.com/andybalholm/brotli v1.2.0 // indirect
	github.com/apache/thrift v0.24.0 // indirect
	github.com/beeper/argo-go v1.1.2 // indirect
	github.com/beeper/poly1305 v0.0.0-20250815183548-d4eede7bbf3c // indirect
	github.com/coder/websocket v1.8.15 // indirect
	github.com/coreos/go-systemd/v22 v22.7.0 // indirect
	github.com/dustin/go-humanize v1.0.1 // indirect
	github.com/elliotchance/orderedmap/v3 v3.1.0 // indirect
	github.com/emersion/go-vcard v0.0.0-20241024213814-c9703dde27ff // indirect
	github.com/gabriel-vasile/mimetype v1.4.13 // indirect
	github.com/google/go-querystring v1.2.0 // indirect
	github.com/google/uuid v1.6.0 // indirect
	github.com/icholy/digest v1.1.0 // indirect
	github.com/imroc/req/v3 v3.56.0 // indirect
	github.com/klauspost/compress v1.18.2 // indirect
	github.com/mattn/go-colorable v0.1.15 // indirect
	github.com/mattn/go-isatty v0.0.24 // indirect
	github.com/mattn/go-pointer v0.0.1 // indirect
	github.com/ncruces/go-strftime v1.0.0 // indirect
	github.com/petermattis/goid v0.0.0-20260713124913-97594f28f5ca // indirect
	github.com/quic-go/qpack v0.6.0 // indirect
	github.com/quic-go/quic-go v0.57.1 // indirect
	github.com/refraction-networking/utls v1.8.1 // indirect
	github.com/remyoudompheng/bigfft v0.0.0-20230129092748-24d4a6f8daec // indirect
	github.com/rs/xid v1.6.0 // indirect
	github.com/skip2/go-qrcode v0.0.0-20200617195104-da1b6568686e // indirect
	github.com/tidwall/gjson v1.19.0 // indirect
	github.com/tidwall/match v1.2.0 // indirect
	github.com/tidwall/pretty v1.2.1 // indirect
	github.com/tidwall/sjson v1.2.5 // indirect
	github.com/vektah/gqlparser/v2 v2.5.27 // indirect
	github.com/yuin/goldmark v1.8.4 // indirect
	go.mau.fi/libsignal v0.2.2 // indirect
	go.mau.fi/webp v0.3.0 // indirect
	go.mau.fi/zeroconfig v0.2.0 // indirect
	golang.org/x/crypto v0.54.0 // indirect
	golang.org/x/exp v0.0.0-20260709172345-9ea1abe57597 // indirect
	golang.org/x/image v0.44.0 // indirect
	golang.org/x/net v0.57.0 // indirect
	golang.org/x/sync v0.22.0 // indirect
	golang.org/x/sys v0.47.0 // indirect
	golang.org/x/term v0.45.0 // indirect
	golang.org/x/text v0.40.0 // indirect
	google.golang.org/protobuf v1.36.11 // indirect
	gopkg.in/natefinch/lumberjack.v2 v2.2.1 // indirect
	modernc.org/libc v1.74.4 // indirect
	modernc.org/mathutil v1.7.1 // indirect
	modernc.org/memory v1.11.0 // indirect
)

// The WhatsApp bridge lives as a locally-vendored copy under infra/matrix-native
// (regenerated by the native-stack build scripts; not committed to git). The
// engine builds against it directly so behaviour matches the proven Stage 0 spike.
replace go.mau.fi/mautrix-whatsapp => ../infra/matrix-native/src-whatsapp

// The Signal bridge (also bridgev2, already pinned to mautrix v0.29.1) lives as a
// locally-vendored copy under infra/matrix-native/src-signal. Building with Signal
// links libsignal (Rust) via cgo — libsignal_ffi.a must be on the linker path.
replace go.mau.fi/mautrix-signal => ../infra/matrix-native/src-signal

// The Meta bridge (Instagram + Messenger, bridgev2, pinned to mautrix v0.29.1)
// lives as a locally-vendored copy under infra/matrix-native/src-meta. Pure Go
// (no extra native lib beyond what signal already links).
replace go.mau.fi/mautrix-meta => ../infra/matrix-native/src-meta

// src-meta uses Beeper's req/v3 fork (compatible with the resolved qpack); a
// dependency module's replace isn't inherited, so the engine must declare it too.
replace github.com/imroc/req/v3 => github.com/beeper/req/v3 v3.0.0-20260703124114-47a4e2aa147e
